### ISSUE TITLE
Lepidopter update-1 missing files and config

### ISSUE THREAD

**Issue by anadahz** [OpenObservatory/lepidopter-update#3]
This is to keep track of the changes need to happen in update-1.

The following files need to added:

```
lepidopter-fh/etc/default/rcS
lepidopter-fh/etc/crontab
lepidopter-fh/etc/default/hwclock
```

We should copy `/etc/localtime` to `/usr/share/zoneinfo/UTC`

When the quota function is ready we need to add the following config line:
`measurement_quota: 1G`

**Comment by hellais** [comment]
> The following files need to added:

Will add those to the update script.

> We should copy /etc/localtime to /usr/share/zoneinfo/UTC

Will do.

> When the quota function is ready we need to add the following config line:

It is ready and there is no need to add that config line option as it is the default.
